version: "3"
services:
  # Для запуска приложения запустите: docker-compose up web
  web:
    image: nginx:1.17-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/config/nginx.conf
      - ./:/code
    command: nginx -c /config/nginx.conf
    user: root
    ports:
      - "8080:8080"
    depends_on:
      - fpm
      - redis
      - mysql
    stop_signal: SIGTERM

  # Процесс fpm
  fpm:
    build: ./docker/php
    volumes:
      - ./:/code
#    environment:
#      REDIS_HOST: redis
#      MYSQL_HOST: mysql
#      MYSQL_PORT: 3306
#      MYSQL_PASSWORD: secret
#      MYSQL_DATABASE: views
#      MYSQL_USER: user
#    links:
#      - mysql
#      - redis

  # MySQL
  mysql:
    image: "mysql:8.4.0"
#    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: views
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
    volumes:
        - database:/var/lib/mysql
    ports:
      - "33061:3306"

  # Redis
  redis:
    image: "redis:6.0.2-alpine"

  # Для запуска тестов запустите: docker-compose up tests
  tests:
    build: ./docker/php
    command: /usr/local/bin/codecept run -vvv
    volumes:
      - ./:/code
    depends_on:
      - web

  # Для запуска терминала с настроенной средой php запустите: docker-compose run terminal
  terminal:
    build: ./docker/php
    entrypoint: /bin/sh
    volumes:
      - ./:/code

volumes:
  database: